@echo off
rd NBear.Common.Design\bin /s/q
rd NBear.Common.Design\obj /s/q
rd NBear.Common\bin /s/q
rd NBear.Common\obj /s/q
rd NBear.Data\bin /s/q
rd NBear.Data\obj /s/q
rd NBear.IoC\bin /s/q
rd NBear.IoC\obj /s/q
rd NBear.Net\bin /s/q
rd NBear.Net\obj /s/q
rd NBear.Test.UnitTests\bin /s/q
rd NBear.Test.UnitTests\obj /s/q
rd NBear.Test.CaseTests\bin /s/q
rd NBear.Test.CaseTests\obj /s/q
rd NBear.Tools.DbToEntityDesign\bin /s/q
rd NBear.Tools.DbToEntityDesign\obj /s/q
rd NBear.Tools.EntityDesignToEntity\bin /s/q
rd NBear.Tools.EntityDesignToEntity\obj /s/q
rd NBear.Tools.EntityDesignToEntityVsPlugin\bin /s/q
rd NBear.Tools.EntityDesignToEntityVsPlugin\obj /s/q
rd SetupNBearVsPlugin\bin /s/q
rd SetupNBearVsPlugin\obj /s/q
rd NBear.Tools.ConfigurationEncrypter\bin /s/q
rd NBear.Tools.ConfigurationEncrypter\obj /s/q
rd NBear.Web\bin /s/q
rd NBear.Web\obj /s/q
rd NBear.Web.Data\bin /s/q
rd NBear.Web.Data\obj /s/q
rd NBear.IoC.Hosts.ServiceHost\bin /s/q
rd NBear.IoC.Hosts.ServiceHost\obj /s/q
rd NBear.IoC.Servers.ServiceMQServer\bin /s/q
rd NBear.IoC.Servers.ServiceMQServer\obj /s/q
rd NBear.MVP\bin /s/q
rd NBear.MVP\obj /s/q
rd TestResults /s/q